### ISSUE TITLE
MP-DCCP Concept

### ISSUE THREAD

**Issue by boucadair** [markusa/ietf-multipath-dccp#113]
```
           Host A                               Host B
------------------------             ------------------------
Address A1    Address A2             Address B1    Address B2
----------    ----------             ----------    ----------
  |             |                      |             |
  |         (DCCP subflow setup)       |             |
  |----------------------------------->|             |
  |<-----------------------------------|             |
  |             |                      |             |
  |             |  (DCCP subflow setup)|             |
  |             |--------------------->|             |
  |             |<---------------------|             |
  | merge individual DCCP subflows to one multipath connection
  |             |                      |             |
```
I know that almost all this text is "grabbed" from 6824, but I think some clarity is needed:
* make it clear that MP-DCCP does not require the presence of more than one address in both peers.
* Add some text that the logic for adding/removing subflows is policy-based and implementation-specific

**Comment by dirkhugo** [comment]
in my understanding MP-DCCP only needs more than one interface/IP address at the sender side as shown in the figure, the receiver (or aggregation point in between) may or even must only use one - and surely the detailed procedures for subflow management are out of scope here. I would draft some corresponding text if authors agree ...
