### ISSUE TITLE
How to signal a maximum number of paths per connection

### ISSUE THREAD

**Issue by boucadair** [markusa/ietf-multipath-dccp#120]
Some peers may try to establish a full mesh subflows, while this is not optimal. Some means to notify the peer about the max number of simultaneous paths would solve that issue

**Comment by markusa** [comment]
@boucadair
upon your request in #113  we changed text in #145 to clarify that path management logic is implementation specific. In this context I wonder why it is helpful to signal the maximum number of accepted paths?
Furthermore it is not known to me that MPTCP or MP-QUIC provide this feature.

**Comment by boucadair** [comment]
MP-QUIC limits it to the number of available CIDs. For MPTCP, there is https://datatracker.ietf.org/doc/html/rfc8041#section-3.3, FWIW: 

```
When the server is multihomed, using the full-mesh subflow manager
   may lead to a large number of subflows being established.  For
   example, consider a dual-homed client connected to a server with
   three interfaces.  In this case, even if the subflows are only
   created by the client, six subflows will be established.  This may be
   excessive in some environments, in particular when the client and/or
   the server have a large number of interfaces.  Implementations should
   limit the number of subflows that are used. 
```
