### ISSUE TITLE
align formatting of MP sub-options description 

### ISSUE THREAD

**Issue by dirkhugo** [markusa/ietf-multipath-dccp#155]
TLV parameters of MP-DCCP sub-options in the figures use different formats (Length=..., binary value or just Length with value in dec provided in legend below) - should be harmonized / unified IMO

**Comment by markusa** [comment]
@dirkhugo I checked all Length descriptors in the #MP_OPT section and I did not find any inconsistency. Maybe I overlooked something?
Can you point me to the right lines or better send a PR?

**Comment by dirkhugo** [comment]
right, that improves the consistency - only for OPT_7 -OPT_9 we still have 'Type' in the figure instead of '00101110' (as for OPT_0 to OPT_6 and OPT_10 ...
