### ISSUE TITLE
In Table 6, feature value should be 10 (not 0x10)

### ISSUE THREAD

**Issue by rjaksa** [markusa/ietf-multipath-dccp#160]
In Section 8 IANA considerations, Table 6, the _Value_ for the **MP-DCCP capability feature** should be '10' not '0x10' (16 in decimal).

**Comment by markusa** [comment]
Thank you @rjaksa , fixed in https://github.com/markusa/ietf-multipath-dccp/commit/c3a4368db9770f06e710090c6d77642b9246481e
