### ISSUE TITLE
Editorial nits, introduction

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#162]
"MP-DCCP can be applied for load-balancing, seamless session handover, and aggregation purposes"

I suggest to:
s/aggregation/bandwidth aggregation

**Comment by sferlin** [comment]
"As pointed out in I-D.amend-tsvwg-multipath-framework-mpdccp the proposed encapsulation in terms of lightweight DCCP flow headers is more appropriate for unreliable IP traffic in terms of UDP and other non-TCP packets in comparison to MPTCP. Such considerations are not detailed in the present specification."

I find this text block slightly misplaced in the current paragraph. I would move it to some other place in the introduction, as it the text that follows does not refer back here.

**Comment by sferlin** [comment]
"not to be mixed up with the "application sub-flows""

I suggest to:
s/sub-flows/subflows

**Comment by sferlin** [comment]
In Figure 2, one of the text following the sequence diagram say "merge individual DCCP subflows to one multipath connection"

I suggest:
s/multipath connection/MP-DCCP connection

**Comment by sferlin** [comment]
"MP-DCCP identifies multiple paths by the presence of multiple addresses at hosts. " right before this sentence, explaining Figure 2, you also write "It should be noted that MP-DCCP does not require the presence of more than one address in both peers.".

I think this may sound confusing for someone looking at Figure 2, which indeed only uses Address B1 of Host B, but still establishes a MP-DCCP connection with Host A.
Maybe remove the first mention in the text.

**Comment by sferlin** [comment]
"Although this additional session is shown as being initiated from A2, it could equally have been initiated from B1 or B2."

I session the right word here? The draft talks about subflow a few lines before.

**Comment by dirkhugo** [comment]
tried to address the aspects in branch on #161 
https://github.com/markusa/ietf-multipath-dccp/tree/161-editorial-nit-abstract
