### ISSUE TITLE
Editorial nits, operational overview

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#163]
"allows multiple application sub-flows"

s/sub-flows/subflows

**Comment by sferlin** [comment]
"as a generic multiplexing facility, can not fully support multiple congestion control mechanisms for multiple DCCP flows between same source and destination addresses."

s/DCCP flows/DCCP subflows

**Comment by dirkhugo** [comment]
here as before we quote the wording of RFC4340 using expression "application sub-flow" - we may put the quotation marks here again to emphasize that (while subflows as used in this document address the "splitted" DCCP flows) so I would suggest to not change it as proposed

**Comment by abrunstrom** [comment]
We use application subflow at multiple other locations as well, so changed it to subflow here and just left the quoted part from RFC4340 as sub-flow.
