### ISSUE TITLE
UDP and IP

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#166]
I would recommend adding to the draft that a few MPDCCP core components such as scheduler, congestion control (mentioned later) and path management (? - or other name, adopted here from MPTCP) are not part of this draft. The authors have a sentence "The number of concurrent DCCP subflows can vary during the lifetime of a Multipath DCCP connection.", which leave the reader at the point where it appears, without enough information.

**Comment by dirkhugo** [comment]
In principle this is mentioned as out of scope in different sections, but we may add right after that sentence above (i.e., at the end of ch. 2) something like:
"Details of procedures and criteria for transmission scheduling, path management methods, and the decision on use of specific congestion control profiles is out of scope of this document. Considerations on the latter issue are provided in sect. 3.6."

**Comment by dirkvhugo** [comment]
Great to see work continues - BTW FYI my okd account won't wprk anymore so I created a new one ;-/ ... and still happy to help!
