### ISSUE TITLE
MP_HASH

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#167]
MP_HASH is very shortly mentioned in MP_HMAC. I wonder if
- "Therefore, a MP_HASH MUST directly follow its associated multipath option" could be extended and better explained in the MP_HMAC context
- If MP_HMAC itself is limited to MP_(JOIN, ADDADDR, REMOVEADDR) or _FASTCLOSE and _CLOSE shouldn't be added.

**Comment by markusa** [comment]
@sferlin 
can you please provide your feedback to #174 which aims to solve your first bulletpoint.

Regarding your second bulletpoint:
 >     * If MP_HMAC itself is limited to MP_(JOIN, ADDADDR, REMOVEADDR) or _FASTCLOSE and _CLOSE shouldn't be added.
I have clarity questions. Do you think there is a confusion in the draft? In the description of MP_HMAC, the scope is clearly defined for MP_(JOIN, ADDADDR, REMOVEADDR). Also the individual descriptions of MP_(JOIN, ADDADDR, REMOVEADDR) mention the combined usage with MP_HMAC. 
Contrary, the description of _FASTCLOSE and _CLOSE does not teach the use of MP_HMAC and, to protect against misuse, defines KeyData.
What needs to be improved?
