### ISSUE TITLE
CCID

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#168]
CCID is mentioned in isolation in Section 3.2.7.

**Comment by dirkhugo** [comment]
I think this can be easily resolved by adding the definition in sect. 2 after 
"... can not fully support
   multiple congestion control mechanisms for multiple DCCP flows
   between same source and destination addresses." following text:
 "Various congestion control mechanisms have been specified to optimize DCCP performance for specific traffic types in terms of profiles denoted by a Congestion Control IDentifier (CCID)."

**Comment by andrkass** [comment]
Thanks, i talked with Simone and this will solve her issue. I will create PR
