### ISSUE TITLE
MP_CONFIRM

### ISSUE THREAD

**Issue by sferlin** [markusa/ietf-multipath-dccp#169]
You mention in Section 3.2.1 that in some operations an MP_CONFIRM is required. Is it the case only for MP_(ADDADDR, REMOVEADDR, PRIO)? I miss a bit error handling in some cases where you do not need a MP_CONFIRM in the current draft, but you might want to signal that an operation has failed e.g. MPDCCP protocol version. You have the Fallback Section at the end, for an implementer it would be useful to have it as you describe the options.

**Comment by NathalieRM** [comment]
Hi @sferlin ,

MP_CONFIRM is indeed only required for MP_ADDADDR, MP_REMOVEADDR and MP_PRIO. I added some lines specifying error handling for the options I considered necessary, please have a look into the PR and let me know if this is OK for you.
