### ISSUE TITLE
Replace "Feature 10" with "THIS-FEATURE"

### ISSUE THREAD

**Issue by markusa** [markusa/ietf-multipath-dccp#210]
```
Please not Feature 10 has NOT been assigned. I suggest you replace all 
occurrences of “10” with “THIS-FEATURE” and add a note that IANA is 
requested to allocate a feature number for this use.
```
- As soon as adopted, I would happily accept an IANA request for a 
provisional allocation of feature number 10 for this RFC-to-be. Also  
you can then request DCCP Reset Code value 13.

**Comment by markusa** [comment]
Wouldn't this also affect all occurrences of DCCP Reset Code 13?

**Comment by gorryfair** [comment]
It applies to any new IANA assignment.
