### ISSUE TITLE
MP_PRIO sense of Secondary path defintion?

### ISSUE THREAD

**Issue by markusa** [markusa/ietf-multipath-dccp#60]
What is the sense of the current Secondary path, , as outlined below, definition if `3-15` can be used instead?

Assume a path with prio `15` and another with a lower prio value, e.g., prio `14`, the lower prio path behaves like Secondary, right?

```
                       1                   2                   3
   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  +---------------+---------------+-------+-------+--------------+
  |     Type      |     Length    |Subtype| Prio  | AddrID       |
  +---------------+---------------+-------+-------+--------------+

The following values are available for Prio field:

*  0: Do not use.  The path is not available.

*  1: Standby: do not use this path for traffic scheduling, if
  another path (secondary or primary) is available.

*  2: Secondary: do not use this path for traffic scheduling, if the
  other paths are good enough.  The path will be used occasionally,
  e.g. when primary paths are congested or become not available.

*  3: Primary: can use the path in any way deemed reasonable by peer.
  Will always be used for packet scheduling decisions.

*  4 - 15: relative priority of one path over the other to give
  relative path priority for primary paths.  The peer should
  consider sending more traffic over higher priority path.  Higher
  numbers indicate higher priority.
```

@andrkass @abrunstrom @NathalieRM

**Comment by andrkass** [comment]
I would say no, but rather both are Primary and both now have almost equal priority.

**Comment by dirkhugo** [comment]
I agree with Andreas, all 3-15 are primary and should be considered in usage for packet scheduling while 2 only in case of temporary degradations of higher prio and 1 only in case of complete loss of 2-15 (but how to distinguish between temporary and complete loss is surely 'implementation specific' ...)

**Comment by andrkass** [comment]
do we need 1 sentence clarifictaion?

**Comment by markusa** [comment]
After this discussion not necessarily, unless others have the same understanding that a path Prio combination of:

```
Path 1 | Path 2
   2   |   15
```
results in the same as:
```
Path 1 | Path 2
  14   |   15
```

In any case, and according to my expectation, the low priority path is only used when the high priority path is congested.

**Comment by markusa** [comment]
As discussed in our last telephone conversation, I prefer to use the term "Backup" rather than "Secondary".
